<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
    <PackageReference Include="WinSCP" Version="6.5.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Model.BO.Data\Model.BO.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

</Project>
